# Generated by Django 5.1.4 on 2025-01-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_message_messagenotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='hospital_profiles/'),
        ),
    ]
