# Generated by Django 5.1.4 on 2025-02-11 09:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_donor_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('organ', 'Organ'), ('tissue', 'Tissue'), ('stem_cell', 'Stem Cell')], max_length=20)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrganDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('agreed_to_donate', models.BooleanField(default=False)),
                ('registration_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.donor')),
                ('organs', models.ManyToManyField(related_name='donors', to='core.organtype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_age', models.PositiveIntegerField()),
                ('patient_blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('urgency_level', models.IntegerField(choices=[(1, 'Normal'), (2, 'Urgent'), (3, 'Critical')])),
                ('medical_notes', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hospital')),
                ('organ_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organtype')),
            ],
        ),
        migrations.CreateModel(
            name='OrganDonorMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('organ_donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organdonor')),
                ('organ_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organrequest')),
            ],
            options={
                'unique_together': {('organ_request', 'organ_donor')},
            },
        ),
    ]
