# Generated by Django 5.1.4 on 2025-02-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_organtype_organdonor_organrequest_organdonormatch'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrganDonorMatch',
        ),
    ]
