# Generated by Django 5.1.4 on 2025-02-11 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_organdonormatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='organrequest',
            name='matched_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='core.organdonor'),
        ),
    ]
