# Generated by Django 5.1.4 on 2025-02-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_organrequest_matched_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organtype',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='organtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
