# Generated by Django 5.1.4 on 2025-02-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_organtype_description_alter_organtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organdonor',
            name='donor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Organdonor', to='core.donor'),
        ),
    ]
