# Generated by Django 5.1.4 on 2025-02-25 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_organdonor_donor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
    ]
