# Generated by Django 5.1.4 on 2025-02-25 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_donor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blood Donor', 'verbose_name_plural': 'Blood Donors'},
        ),
    ]
